### ISSUE TITLE
default rules list during installation

### ISSUE THREAD

**Issue by EliyahuStern** [jzdziarski/littleflocker#39]
The first usage of the tool is pretty cumbersome. The user is flooded by prompts for even the most basic operations of the OS (I had a prompt asking to allow Finder, Xcode, and even Little Flocker Configuration app itself, access files).

Suggested enhancement: provide an option to pre-set a default rules list during installation (users will probably help build it as they see their favorite legit tool being blocked). Such list can also be used as a reference for rules system usage.

Note: As I already use the tool for some time (I have v0.0.72 installed) this issue might not be relevant anymore.

**Comment by jzdziarski** [comment]
Hi, thanks for the feedback. There is a pretty big list of preloaded app rules already programmed in, but a few are intentionally left out. Finder requires rather broad access ("any" is usually necessary), and so I leave that up to the user, as some people use finder alternatives (like Path Finder). Xcode is quite a big project, and I know the popups are frustrating, but only a small percentage of users are running Xcode so it really needs to be left up to the user. Custom rules allowing prefix "/Applications/Xcode.app/" seem to greatly reduce the popups for Xcode, although some people might want to configure everything manually.

It's gotten a lot better since 0.0.72 but there will always be custom rules that need to be added.

**Comment by jmsdnns** [comment]
I would like to second this. My experience with both using git and dropbox is that I'm somewhat overwhelmed by prompts.

It would great if there was a way I could say something like, _"I use git in ~/Projects, please don't both me if I'm editing files that are part of a repo"_ I have no idea how complicated this is, so it might be unrealistic, but it would be very helpful.

As for dropbox, I can't get myself to a place where I don't want to be told anytime something checks out the dropbox directory, but I still feel somewhat overwhelmed by the number of prompts.

**Comment by jzdziarski** [comment]
I usually just specify ~/Projects when I get prompted; I may get prompted two or three times, one for git, one for git-remote-http, etc., but not to an overwhelming degree

**Comment by jmsdnns** [comment]
Ohhh... I see! I am new to Little Flocker so I missed that, but it works as you described! thank you.

**Comment by jzdziarski** [comment]
@EliyahuStern that might be a good strategy for you as well, for Finder, select either "Any" or at least a larger path of files you want it to have access to (e.g. ".../Downloads/") then click Forever, and Allow. It shouldn't be prompting you so much once you get up the initial rules.

**Comment by EliyahuStern** [comment]
Thanks,

I have opened the request since I remember it was an overwhelming first experience, but I don't really remember the specifics. I just think it might push away non-power users and make them uninstall altogether...

I plan to upgrade soon, so I'll try to remove the current rules and make it a clean install. I will comment about my second first experience later ;)

**Comment by cybershambles** [comment]
Consider a white/black and gray list?
Gray basically being "recommended, but not enforced"... so it'll let people who are less inclined to click the gray list choice?

**Comment by jzdziarski** [comment]
the first boot can be a doozy if you have a lot of software installed. i am considering a "silent mode" that allows everything, but this too can have unintended consequences, especially if you have malware lurking on your system. unlike Little Snitch, where it's just a network connection, allowing everything means that something could plant itself in your startup folder and persist on your system. so figuring out the right tradeoff between security and usability is the challenge.

**Comment by jzdziarski** [comment]
0.99.5 now has a "learning mode" that runs from first boot until 10 seconds after you've logged in and learns / allows all access, then presents you with a rules list to import. You can also turn on learning mode any time from the menu to train a new application, if you don't feel like dealing with popups. The trade-off is that you're not protected when learning mode is on, so you should only run it on a system you believe to be secure. At any rate, it's really good about catching all that first time stuff that normally you'd have to deal with.

**Comment by EliyahuStern** [comment]
How about having a check list of installed apps at the end of the installation, where you can select which apps will be included in "allow any" list on first boot? This can minimize the risk for malware planting itself, and give a much smooth first flow.

**Comment by jzdziarski** [comment]
I just pushed beta 2, and have added something very similar to this. The first run after install, LF goes into learning mode for boot and 10 seconds after boot, then prompts the user with suggested rules. You can also turn on this learning mode to train any new apps, and have it present you with suggestions as well. Note that because learning mode is permissive during the training period, you're not protected while it is running, but will at least get a report of all the apps that accessed content during that period.

**Comment by tomtastic** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/302127/18381845/290feda0-7676-11e6-8d43-b8830496b0b1.jpg)
Why can't I approve this rule 'forever', shouldn't it be a default rule, and why are we storing the rc file in /Users/Shared?

**Comment by jzdziarski** [comment]
it just seemed to make sense that if you're going to edit your rules, it should always ask you permission first, a lot of potential there for malicious apps to try and take advantage of that.

**Comment by jzdziarski** [comment]
pretty satisfied with how this has turned out in beta 6, so going to close this
