### ISSUE TITLE
signed app access to its Group Containers dir

### ISSUE THREAD

**Issue by prenagha** [jzdziarski/littleflocker#4]
Noticed a few cases where Mac App Store apps, that are presumably signed and installed correctly, do not get default access to their related "Group Containers" directory. Wasn't sure if that was something you can solve for, but would think for signed app store apps granting default access to that would be a good idea and align with the intent of the recent setting change related to caches/logs... for signed apps
![sc_2016816_214635_155](https://cloud.githubusercontent.com/assets/194250/17721898/c1873b5c-63fb-11e6-8fd0-f48cfb09dcd8.png)

**Comment by jzdziarski** [comment]
Group containers appear to be rather ad-hoc in nomenclature, and don't seem to appear in the app's Info.plist file, so I've not been able to find a safe way to allow them without the user first granting permission.

**Comment by jzdziarski** [comment]
Confirmed, it appears that group containers are accessed methodically rather than specified as individual entitlements in the Info.plist, so unfortunately the only two choices are to whitelist all group containers, or allow the user to decide. For now, going to err on the side of the user, as some applications are likely to store sensitive content in these folders.
