### ISSUE TITLE
When adding a rule to allow Applescript, use "r" instead of "rwc"

### ISSUE THREAD

**Issue by brad2014** [jzdziarski/littleflocker#62]
Suggestion:  When creating the rule for LittleFlockerAlertTypeAppleScript, give "r" permission rather than "rwc", on the presumption that Applescript users should not be altering that system directory.

**Comment by jzdziarski** [comment]
might end up being more confusing than it is now, since we grant rwc by default for everything (user has no option to choose read-only privs, for example); i get your point though; we're not watching that folder for write or create anyway (and it's protected by SIP), so there's no harm in keeping it, but if we get to a point where we control r/w/c individually, this might make sense in the future.

**Comment by jzdziarski** [comment]
that mode button I was talking about is now in the nightly build, and will eventually make its way to a release
